#!/usr/bin/env bash
# generate-changelog.sh — Generate a structured CHANGELOG.md from git history
# Groups commits since the last tag into Added, Fixed, Changed, Removed sections.

set -euo pipefail

OUTPUT="${1:-CHANGELOG.md}"

LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [ -n "$LAST_TAG" ]; then
    RANGE="${LAST_TAG}..HEAD"
    echo "→ Scanning commits since tag: $LAST_TAG"
else
    RANGE="HEAD"
    echo "→ No tags found — scanning all commits"
fi

declare -a ADDED FIXED CHANGED REMOVED

while IFS= read -r line; do
    hash="${line:0:7}"
    subject="${line:8}"
    lowered=$(echo "$subject" | tr '[:upper:]' '[:lower:]')

    if echo "$lowered" | grep -qE '^(feat|add|new|implement|introduce|create)'; then
        ADDED+=("$subject")
    elif echo "$lowered" | grep -qE '^(fix|bug|resolve|patch|hotfix|correct)'; then
        FIXED+=("$subject")
    elif echo "$lowered" | grep -qE '^(remove|drop|delete|deprecate|retire)'; then
        REMOVED+=("$subject")
    else
        CHANGED+=("$subject")
    fi
done < <(git log "$RANGE" --no-merges --pretty=format:"%h %s" 2>/dev/null)

TOTAL=$((${#ADDED[@]} + ${#FIXED[@]} + ${#CHANGED[@]} + ${#REMOVED[@]}))
if [ "$TOTAL" -eq 0 ]; then
    echo "→ No commits found in range: $RANGE"
    exit 0
fi

DATE=$(date +%Y-%m-%d)
VERSION="${LAST_TAG:-unreleased}"

{
    echo "# Changelog"
    echo ""
    echo "## [$VERSION] — $DATE"
    echo ""
    echo "> Auto-generated from $TOTAL commits"
    echo ""

    for category in "Added:ADDED" "Fixed:FIXED" "Changed:CHANGED" "Removed:REMOVED"; do
        IFS=':' read -r label arrname <<< "$category"
        eval "count=\${#${arrname}[@]}"
        if [ "$count" -gt 0 ]; then
            echo "### $label"
            echo ""
            eval "for item in \"\${${arrname}[@]}\"; do echo \"- \$item\"; done"
            echo ""
        fi
    done

    echo "---"
    echo "*Generated by generate-changelog.sh*"
} > "$OUTPUT"

echo "✅ CHANGELOG.md generated: ${#ADDED[@]} added, ${#FIXED[@]} fixed, ${#CHANGED[@]} changed, ${#REMOVED[@]} removed"
